### ISSUE TITLE
REMOVED

### ISSUE THREAD

**Issue by raffaelemancuso** [Synthaze/bibtools#2]
REMOVED

**Comment by Synthaze** [comment]
Hi,

Papers on scihub may be preprint or peer-reviewed items depending on luck.

Next, `bibtools` is designed as a tool you can use to retrieve papers and metadata **without** any institutional credentials.

Finally, the way credentials are used may vary from one institution to the other: you may have direct access to papers through pubmed interface once logged in, or you may need to browse papers in a dedicated interface unrelated to pubmed, etc... In addition to other problems, writing a unified code that solve all these cases would then be difficult to achieve (e.g., I would need a set of credentials to write the corresponding codes). 

And finally, using your credentials this way would be a violation of your university's rules (you can't use them to automatically download papers).

**Comment by raffaelemancuso** [comment]
REMOVE

**Comment by Synthaze** [comment]
FYI this is a general rule. You cannot use your institutional credentials to automatically download papers. That's in Elsevier and other's terms. It is even forbidden in some dimensions to bulk download open-access papers on PMC with automated processes (see rules at https://www.ncbi.nlm.nih.gov/pmc/tools/openftlist/). 

But if you don't believe, ask your uni :).
